import { ReactNode } from "react";
import type { Metadata } from "next";
import { Syncopate } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "../styles/CompactNavbarStyle.css";
import "../styles/globals.css";

const syncopate = Syncopate({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-syncopate",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`${syncopate.className} box-border`}>
        <Header />
        <main className="mt-[8.5rem] max-xs:mt-14">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
