import type { Metadata } from "next";
import { Syncopate } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const syncopate = Syncopate({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-syncopate",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`${syncopate.className}`}>{children}</body>
    </html>
  );
}
